# -*- org-src-preserve-indentation: t; -*-
#+title: Scrapper para DataBursatil
#+author: Eduardo Gomezcaña
#+property: header-args :tangle ../src/databursatil.py

* Librerías
No se requieren muchas librerías para realizar el /scrap/, basta uasr la
/requests/ para manejar las transacciones, /json/ para obtener objetos de las
cadenas con las que responde la /API/ y una serie de manejo de fechas para
organizar correctamente la información que se consulta.
#+begin_src python
import requests,json
from datetime import date, timedelta
#+end_src

* Clase base
** Declaración
Esencialmente el módulo define una clase, el /scrapper/ de la API para
DataBursatil.
#+begin_src python
class DataBursatil:
    """Clase muy simple para contactar con la API de DataBursatil"""
    token = None
#+end_src
** Constructor
La /API/ de /DataBursatil/ exige un token que puede obtenerse de manera
gratuita. Para poder inicializar la clase y poder generar las consultas, el
objeto debe inicializarse con ese token.
#+begin_src python
    def __init__ (self, user_token):
        self.token = user_token
#+end_src
* Métodos auxiliares
** Cálculo de fechas
Es útil saber qué semanas han sido completadas para obtener la lista de precios
completa. Para esto, esta función genera todos los inicios de semana (lunes)
desde el lunes inmediato anterior ~init~ hasta el lunes inmediato anterior de
una semana completa antes de ~end~. Esto quiere representar cada semana donde
toda la información ya está disponible desde ~init~ hasta ~end~. En este caso
particular, como las casas de bolsa no operan en fin de semana, una vez que se
detecta que la fecha es viernes, sábado o domingo, la semana se considera
completa y puede usarse directamente.
#+begin_src python
    @staticmethod
    def _mondays_between (init, end):
        """Pequeña función que genera una lista con todos los viernes entre las
        fechas que se introducen"""

        days_since_monday_init = init.weekday()
        init_monday = init - timedelta(days=days_since_monday_init)

        days_since_monday_end = end.weekday()
        if days_since_monday_end >= 4:
            end_monday = end - timedelta(days=days_since_monday_end)
        else:
            end_monday = end - timedelta(days=days_since_monday_end + 7)

        weeks = (end_monday - init_monday).days // 7

        if weeks < 0:
            return []

        return [init_monday + timedelta(weeks=i) for i in range(weeks + 1)]
#+end_src
** Semana en curso
Es una pequeña función para generar todas las fechas de la semana dada la fecha
~current_date~; de nuevo, sólo considera los días hábiles de las semana. Es útil
para la agrupación de precios.
#+begin_src python
    @staticmethod
    def _week_list (current_date):
        """Pequeña función que genera una lista con todos los elementos de la
        semana de la fecha que se proporciona"""

        current_monday = current_date - timedelta(days=current_date.weekday())
        current_week   = [current_monday + timedelta(days=i) for i in range(5)]

        return current_week
#+end_src
* Consulta de precios
** Último precio
Usando la información de la API de /DataBursatil/, se genera una /URL/ para
hacer la consulta del último precio reportado del activo indicada con ~ticker~ y
~series~. La respuesta se procesa para devolver un flotante.
#+begin_src python
    def last_price (self, ticker, series="*"):
        """Función para consulta el último precio registrado en la plataforma y
        devolverlo como float"""
        URL = f"https://api.databursatil.com/v2/cotizaciones?token={self.token}&emisora_serie={ticker+series}&concepto=u&bolsa=bmv"
        req = requests.get(URL)
        response = json.loads(req.text)
        return float(response[ticker+series]["bmv"]["u"])
#+end_src
** Histórico
Usando la información de la /API/ de /DataBursatil/, se genera una /URL/ para
hacer la consulta histórica de un activo usando como inicio la fecha ~init~ y
fin la fecha ~end~. La respuesta se procesa para generar un diccionario cuyas
claves son las fechas (objetos del tipo fecha en /python/) y los valores son los
precios reportados por la respuesta.
#+begin_src python
    def price_history (self, init, end, ticker, series="*"):
        """Función para consultar los históricos y devolver un diccionario con
        las fechas de interés"""
        if end == init:
            return {}
        URL  =  "https://api.databursatil.com/v2/historicos?"
        URL += f"token={self.token}&inicio={init.strftime('%Y-%m-%d')}&final={end.strftime('%Y-%m-%d')}"
        URL += f"&emisora_serie={ticker+series}"
        req  = requests.get(URL)
        response = json.loads(req.text)
        return {date.fromisoformat(date_str) : float(response[date_str][0]) for date_str in response.keys()}
#+end_src

** Histórico ponderado
Para no consultar frecuentemente la /API/ es preferible almacenar la información
de manera local, pero registrar todos las fechas en un intervalo no es valioso
considerando que sólo quieren observarse tendencias cercanas. Para simplificar
los registros históricos, se aglutinan por semanas y se obtiene un promedio de
la información disponible por semana, para esto, se pide una fecha de inicio y
fin (~init~ y ~end~) y se calculan los lunes de las semanas que ya terminaron
más cercanas a cada una de estas fechas. Con esta información, se realiza una
consulta que incluya el rango especificado y se procesa para calcular las medias
de cada semana dejando como clave al lunes de cada semana al devolver el
diccionario.
#+begin_src python
    def weekly_mean_price_history (self, init, end, ticker, series="*"):
        """Función para consultar los históricos y devolver un diccionario
        únicamente con las fechas de interés"""
        mondays = self._mondays_between(init,end)

        if len(mondays) < 0 :
            return {}

        prices = self.price_history(init=mondays[0], end=mondays[-1], ticker=ticker, series=series)

        week_mean_prices = {}
        for monday in mondays:
            week_dates  = self._week_list(monday)
            week_prices = [ prices[day] for day in week_dates if day in prices and prices[day] != 0.0 ]
            mean_price = sum(week_prices)/len(week_prices) if len(week_prices) != 0 else 0.0
            week_mean_prices[monday] = round(mean_price,2)

        return week_mean_prices
#+end_src

** Interacción principal
Queremos conectar el /scrapper/ con la base de datos, ese es nuestro principal
objetivo. Con todo lo anterior, la conexión es sencilla y el objetivo es que
pueda usarse de manera transparente con los resultados que se extraen de la base
de datos y de vuelta. En particular, la función ~consult_history_from~ recibe un
diccionario con /symbol+serie/ como claves y la última fecha de la que se tiene
registro. Para cada clave, se intenta llenar los datos que faltan usando el día
actual y llamando a ~weekly_mean_price-history~ con ese propósito para devolver
un diccionario con las mismas claves pero diccionarios que contienen las fechas
y el precio de la moneda en cada caso.
#+begin_src python
    def consult_history_from (self, symbols_dict):
        """Función para consultar los históricos de una lista de activos
        (símbolo+serie) desde una fecha de interés. El diccionario tiene como
        claves símbolo+serie y como valor la fecha desde la cual se debe
        consultar el precio"""

        today = date.today()

        return { (ticker, series) : self.weekly_mean_price_history(init_date, today, ticker, series)
                 for (ticker, series), init_date in symbols_dict.items() }
#+end_src
